const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'components', 'leads', 'OutreachComposerModal.tsx');
let content = fs.readFileSync(filePath, 'utf-8');

// 1. Update imports
content = content.replace(
  "import { generateAIEmailDraft } from '@/app/actions/aiActions';",
  "import { generateAIEmailDraft, generateAITemplateVariables } from '@/app/actions/aiActions';"
);

// 2. Add state
const stateAddition = `  const [customVars, setCustomVars] = useState<Record<string, string>>({});
  const [hasManuallyEdited, setHasManuallyEdited] = useState(false);
  const [aiReviewNeeded, setAiReviewNeeded] = useState<string[]>([]);`;
content = content.replace(
  /const \[customVars, setCustomVars\] = useState<Record<string, string>>\({}\);\s*const \[hasManuallyEdited, setHasManuallyEdited\] = useState\(false\);/,
  stateAddition
);

// 3. Rewrite handleAIGenerate
const oldAIGen = /const handleAIGenerate = async \(\) => \{[\s\S]*?\} finally \{\s*setIsGeneratingAI\(false\);\s*\}\s*\};/;
const newAIGen = `  const handleAIGenerate = async () => {
    setIsGeneratingAI(true);
    setErrorMessage(null);
    setAiReviewNeeded([]);
    try {
      if (detectedVariables.length > 0) {
        // AI Dynamic Variables Mode
        const activeTemplate = dynamicTemplates.find(t => t.id === selectedTemplateId) || dynamicTemplates[0];
        const templateContext = activeTemplate.subject + "\\n\\n" + activeTemplate.body;
        
        const result = await generateAITemplateVariables(lead, detectedVariables, templateContext);
        if (result.success && result.data) {
          const generatedVars = result.data;
          const newVars = { ...customVars };
          const needsReview: string[] = [];
          
          Object.keys(generatedVars).forEach(key => {
            if (generatedVars[key] === '[NEEDS REVIEW]' || generatedVars[key].includes('REVIEW')) {
              newVars[key] = ''; // Leave it blank or generic so user sees it
              needsReview.push(key);
            } else {
              newVars[key] = generatedVars[key];
              needsReview.push(key); // Mark everything generated by AI as needs review for safety
            }
          });
          
          setCustomVars(newVars);
          setAiReviewNeeded(needsReview);
          playStatusSound('success');
        } else {
          setErrorMessage(result.error || 'Failed to generate AI variables');
        }
      } else {
        // Legacy Generic Email Mode
        const result = await generateAIEmailDraft({
          company_name: lead.company_name,
          contact_person: lead.contact_person,
          targetService: lead.targetService,
          website_url: lead.website_url,
        });
        if (result.success && result.data) {
          setBody(result.data.body || '');
          setSubject(result.data.subject || \`Quick question about \${companyName || lead.company_name}\`);
          setSelectedTemplateId('ai-draft'); 
        } else {
          setErrorMessage(result.error || 'Failed to generate AI email');
        }
      }
    } catch (err: any) {
      setErrorMessage(err.message || 'Error running AI');
    } finally {
      setIsGeneratingAI(false);
    }
  };`;
content = content.replace(oldAIGen, newAIGen);


// 4. Reset aiReviewNeeded when user types in the input manually
// AND Add UI highlight logic
const oldInputs = /<div key=\{v\} className="space-y-1\.5">[\s\S]*?onChange=\{\(e\) => \{[\s\S]*?\}\}[\s\S]*?className="w-full bg-white dark:bg-\[#11131A\] border border-indigo-200 dark:border-indigo-500\/30 rounded-xl px-4 py-2\.5 text-xs text-slate-900 dark:text-white outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500\/20 transition-all font-bold shadow-sm"[\s\S]*?\/>\s*<\/div>/g;

const newInputs = `<div key={v} className="space-y-1.5 relative">
                            <label className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider ml-1">
                              {v.replace(/([A-Z])/g, ' $1').trim()} <span className="text-indigo-500 font-medium">{"{" + v + "}"}</span>
                              {aiReviewNeeded.includes(v) && <span className="ml-2 text-[9px] text-orange-500 font-black animate-pulse">Needs Review</span>}
                            </label>
                            <input 
                              type="text" 
                              value={customVars[v] || ''} 
                              onChange={(e) => {
                                setCustomVars(prev => ({...prev, [v]: e.target.value}));
                                setAiReviewNeeded(prev => prev.filter(k => k !== v));
                              }}
                              className={\`w-full bg-white dark:bg-[#11131A] border rounded-xl px-4 py-2.5 text-xs text-slate-900 dark:text-white outline-none focus:ring-2 transition-all font-bold shadow-sm \${aiReviewNeeded.includes(v) ? 'border-orange-400 dark:border-orange-500 bg-orange-50/50 dark:bg-orange-500/10 focus:border-orange-500 focus:ring-orange-500/20' : 'border-indigo-200 dark:border-indigo-500/30 focus:border-indigo-500 focus:ring-indigo-500/20'}\`}
                            />
                          </div>`;
content = content.replace(oldInputs, newInputs);

fs.writeFileSync(filePath, content, 'utf-8');
console.log('Success');
