export const countryToTimezoneMap: Record<string, string> = {
  'afghanistan': 'AFT (UTC+4:30)',
  'albania': 'CET (UTC+1)',
  'algeria': 'CET (UTC+1)',
  'andorra': 'CET (UTC+1)',
  'angola': 'WAT (UTC+1)',
  'antigua and barbuda': 'AST (UTC-4)',
  'argentina': 'ART (UTC-3)',
  'armenia': 'AMT (UTC+4)',
  'australia': 'AEST (UTC+10)',
  'austria': 'CET (UTC+1)',
  'azerbaijan': 'AZT (UTC+4)',
  'bahamas': 'EST (UTC-5)',
  'bahrain': 'AST (UTC+3)',
  'bangladesh': 'BST (UTC+6)',
  'barbados': 'AST (UTC-4)',
  'belarus': 'MSK (UTC+3)',
  'belgium': 'CET (UTC+1)',
  'belize': 'CST (UTC-6)',
  'benin': 'WAT (UTC+1)',
  'bhutan': 'BTT (UTC+6)',
  'bolivia': 'BOT (UTC-4)',
  'bosnia and herzegovina': 'CET (UTC+1)',
  'botswana': 'CAT (UTC+2)',
  'brazil': 'BRT (UTC-3)',
  'brunei': 'BNT (UTC+8)',
  'bulgaria': 'EET (UTC+2)',
  'burkina faso': 'GMT (UTC+0)',
  'burundi': 'CAT (UTC+2)',
  'cabo verde': 'CVT (UTC-1)',
  'cambodia': 'ICT (UTC+7)',
  'cameroon': 'WAT (UTC+1)',
  'canada': 'EST (UTC-5)',
  'central african republic': 'WAT (UTC+1)',
  'chad': 'WAT (UTC+1)',
  'chile': 'CLT (UTC-4)',
  'china': 'CST (UTC+8)',
  'colombia': 'COT (UTC-5)',
  'comoros': 'EAT (UTC+3)',
  'congo': 'WAT (UTC+1)',
  'costa rica': 'CST (UTC-6)',
  'croatia': 'CET (UTC+1)',
  'cuba': 'CST (UTC-5)',
  'cyprus': 'EET (UTC+2)',
  'czech republic': 'CET (UTC+1)',
  'denmark': 'CET (UTC+1)',
  'djibouti': 'EAT (UTC+3)',
  'dominica': 'AST (UTC-4)',
  'dominican republic': 'AST (UTC-4)',
  'ecuador': 'ECT (UTC-5)',
  'egypt': 'EET (UTC+2)',
  'el salvador': 'CST (UTC-6)',
  'equatorial guinea': 'WAT (UTC+1)',
  'eritrea': 'EAT (UTC+3)',
  'estonia': 'EET (UTC+2)',
  'eswatini': 'SAST (UTC+2)',
  'ethiopia': 'EAT (UTC+3)',
  'fiji': 'FJT (UTC+12)',
  'finland': 'EET (UTC+2)',
  'france': 'CET (UTC+1)',
  'gabon': 'WAT (UTC+1)',
  'gambia': 'GMT (UTC+0)',
  'georgia': 'GET (UTC+4)',
  'germany': 'CET (UTC+1)',
  'ghana': 'GMT (UTC+0)',
  'greece': 'EET (UTC+2)',
  'grenada': 'AST (UTC-4)',
  'guatemala': 'CST (UTC-6)',
  'guinea': 'GMT (UTC+0)',
  'guinea-bissau': 'GMT (UTC+0)',
  'guyana': 'GYT (UTC-4)',
  'haiti': 'EST (UTC-5)',
  'honduras': 'CST (UTC-6)',
  'hungary': 'CET (UTC+1)',
  'iceland': 'GMT (UTC+0)',
  'india': 'IST (UTC+5:30)',
  'indonesia': 'WIB (UTC+7)',
  'iran': 'IRST (UTC+3:30)',
  'iraq': 'AST (UTC+3)',
  'ireland': 'GMT (UTC+0)',
  'israel': 'IST (UTC+2)',
  'italy': 'CET (UTC+1)',
  'jamaica': 'EST (UTC-5)',
  'japan': 'JST (UTC+9)',
  'jordan': 'EET (UTC+2)',
  'kazakhstan': 'ALMT (UTC+6)',
  'kenya': 'EAT (UTC+3)',
  'kiribati': 'GILT (UTC+12)',
  'korea, north': 'KST (UTC+9)',
  'korea, south': 'KST (UTC+9)',
  'kuwait': 'AST (UTC+3)',
  'kyrgyzstan': 'KGT (UTC+6)',
  'laos': 'ICT (UTC+7)',
  'latvia': 'EET (UTC+2)',
  'lebanon': 'EET (UTC+2)',
  'lesotho': 'SAST (UTC+2)',
  'liberia': 'GMT (UTC+0)',
  'libya': 'EET (UTC+2)',
  'liechtenstein': 'CET (UTC+1)',
  'lithuania': 'EET (UTC+2)',
  'luxembourg': 'CET (UTC+1)',
  'madagascar': 'EAT (UTC+3)',
  'malawi': 'CAT (UTC+2)',
  'malaysia': 'MYT (UTC+8)',
  'maldives': 'MVT (UTC+5)',
  'mali': 'GMT (UTC+0)',
  'malta': 'CET (UTC+1)',
  'marshall islands': 'MHT (UTC+12)',
  'mauritania': 'GMT (UTC+0)',
  'mauritius': 'MUT (UTC+4)',
  'mexico': 'CST (UTC-6)',
  'micronesia': 'PONT (UTC+11)',
  'moldova': 'EET (UTC+2)',
  'monaco': 'CET (UTC+1)',
  'mongolia': 'ULAT (UTC+8)',
  'montenegro': 'CET (UTC+1)',
  'morocco': 'CET (UTC+1)',
  'mozambique': 'CAT (UTC+2)',
  'myanmar': 'MMT (UTC+6:30)',
  'namibia': 'CAT (UTC+2)',
  'nauru': 'NRT (UTC+12)',
  'nepal': 'NPT (UTC+5:45)',
  'netherlands': 'CET (UTC+1)',
  'new zealand': 'NZST (UTC+12)',
  'nicaragua': 'CST (UTC-6)',
  'niger': 'WAT (UTC+1)',
  'nigeria': 'WAT (UTC+1)',
  'north macedonia': 'CET (UTC+1)',
  'norway': 'CET (UTC+1)',
  'oman': 'GST (UTC+4)',
  'pakistan': 'PKT (UTC+5)',
  'palau': 'PWT (UTC+9)',
  'panama': 'EST (UTC-5)',
  'papua new guinea': 'PGT (UTC+10)',
  'paraguay': 'PYT (UTC-4)',
  'peru': 'PET (UTC-5)',
  'philippines': 'PHT (UTC+8)',
  'poland': 'CET (UTC+1)',
  'portugal': 'WET (UTC+0)',
  'qatar': 'AST (UTC+3)',
  'romania': 'EET (UTC+2)',
  'russia': 'MSK (UTC+3)',
  'rwanda': 'CAT (UTC+2)',
  'saint kitts and nevis': 'AST (UTC-4)',
  'saint lucia': 'AST (UTC-4)',
  'saint vincent and the grenadines': 'AST (UTC-4)',
  'samoa': 'WST (UTC+13)',
  'san marino': 'CET (UTC+1)',
  'sao tome and principe': 'GMT (UTC+0)',
  'saudi arabia': 'AST (UTC+3)',
  'senegal': 'GMT (UTC+0)',
  'serbia': 'CET (UTC+1)',
  'seychelles': 'SCT (UTC+4)',
  'sierra leone': 'GMT (UTC+0)',
  'singapore': 'SGT (UTC+8)',
  'slovakia': 'CET (UTC+1)',
  'slovenia': 'CET (UTC+1)',
  'solomon islands': 'SBT (UTC+11)',
  'somalia': 'EAT (UTC+3)',
  'south africa': 'SAST (UTC+2)',
  'south sudan': 'CAT (UTC+2)',
  'spain': 'CET (UTC+1)',
  'sri lanka': 'IST (UTC+5:30)',
  'sudan': 'CAT (UTC+2)',
  'suriname': 'SRT (UTC-3)',
  'sweden': 'CET (UTC+1)',
  'switzerland': 'CET (UTC+1)',
  'syria': 'EET (UTC+2)',
  'taiwan': 'CST (UTC+8)',
  'tajikistan': 'TJT (UTC+5)',
  'tanzania': 'EAT (UTC+3)',
  'thailand': 'ICT (UTC+7)',
  'timor-leste': 'TLT (UTC+9)',
  'togo': 'GMT (UTC+0)',
  'tonga': 'TOT (UTC+13)',
  'trinidad and tobago': 'AST (UTC-4)',
  'tunisia': 'CET (UTC+1)',
  'turkey': 'TRT (UTC+3)',
  'turkmenistan': 'TMT (UTC+5)',
  'tuvalu': 'TVT (UTC+12)',
  'uganda': 'EAT (UTC+3)',
  'ukraine': 'EET (UTC+2)',
  'united arab emirates': 'GST (UTC+4)',
  'uae': 'GST (UTC+4)',
  'united kingdom': 'GMT (UTC+0)',
  'uk': 'GMT (UTC+0)',
  'united states': 'EST (UTC-5)',
  'usa': 'EST (UTC-5)',
  'us': 'EST (UTC-5)',
  'uruguay': 'UYT (UTC-3)',
  'uzbekistan': 'UZT (UTC+5)',
  'vanuatu': 'VUT (UTC+11)',
  'vatican city': 'CET (UTC+1)',
  'venezuela': 'VET (UTC-4)',
  'vietnam': 'ICT (UTC+7)',
  'yemen': 'AST (UTC+3)',
  'zambia': 'CAT (UTC+2)',
  'zimbabwe': 'CAT (UTC+2)'
};
